name: Generate Repo

on:
  schedule:
    - cron: '30 * * * *'
  workflow_dispatch:
  repository_dispatch:
    branches:
      - main
    types: [new-release]

jobs:
  generate:
    name: Generate Repo
    runs-on: windows-latest
    steps:
      - name: Extract Branch
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - uses: actions/checkout@v1
      - name: Run Powershell Script
        run: .\generate-repo.ps1
      - name: Commit Files
        continue-on-error: true
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add -A
          git commit -m "Regenerate Repo" --author="${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
      - name: Push Changes
        continue-on-error: true
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.extracted_branch.outputs.branch }}
