name: Update Download Graphs

on:
  schedule:
    - cron: '37 */6 * * *'
  workflow_dispatch:

jobs:
  graphs:
    name: Update Download Graphs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 'pypy3.10'
      - name: Cache Python Environment
        uses: actions/cache@v3
        id: cache-venv
        with:
          path: ./.venv/
          key: ${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-venv-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-venv-
      - name: Install Python Dependencies
        if: steps.cache-venv.outputs.cache-hit != 'true'
        shell: bash
        run: |
          python -m venv ./.venv
          source ./.venv/bin/activate
          python -m pip install -r requirements.txt
      - name: Run Python Script
        run: python gen-graphs.py
      - name: Commit Files
        continue-on-error: true
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add -A
          git commit -m "Regenerate Graphs" --author="${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
      - name: Push Changes
        continue-on-error: true
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
